# Generated by Django 3.0 on 2019-12-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='active',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.AddField(
            model_name='customer',
            name='passwod',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=False, max_length=11),
        ),
    ]
